---
- name: Restart external-node service
  community.docker.docker_compose_v2:
    project_src: "{{ configuration_directory }}"
    files: "{{ docker_compose_files }}"
    state: restarted
    services:
      - external_node
